services:
  _defaults:
    autowire: true
    autoconfigure: true
  sulu_range:
    class: SevenGroupFrance\SuluCustomToggleBundle\Content\Types\CustomToggle
    tags: [{ name: "sulu.content.type", alias: "custom_toggle" }]
